# reference https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11437142#content
# https://travis-ci.org/wangyan100/docker-react
# to tell travis ci , need sudo user right
sudo: required
services:
  # travis will create a docker container
  - docker

before_install:
  # -t will tag image with tagname wangyan100/docker-react
  - docker build -t wangyan100/docker-react -f Dockerfile.dev .

# script section is the script for running test
script:
  # -- --converage is the trick to let npm run test to return result with test converage report, otherwise it will hang there wait for input from user
  - docker run -e CI=true wangyan100/docker-react npm run test -- --coverage

before_deploy: "echo 'ready?'"
# add deployment
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-235134183621"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
